import { authOptions } from './api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';
import { useSession } from 'next-auth/react';
import prisma from '../lib/prisma';

import NewBudget from '../components/new-budget';
import Layout from '../components/layout';
import Head from 'next/head';
import NextLink from 'next/link';

import {
  Box,
  Button,
  Card,
  CardBody,
  CircularProgress,
  CircularProgressLabel,
  Flex,
  Heading,
  Skeleton,
  Spacer,
  Stack,
  Text,
  useColorMode,
} from '@chakra-ui/react';
import { GetServerSidePropsContext } from 'next';

interface Budget {
  id: string,
  name: string,
  desc?: string,
  budget: number,
  expend: number,
}

interface Props {
  budgets: Budget[]
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getServerSession(context.req, context.res, authOptions);

  if (!session || !session?.user?.email)
    return {
      props: { budgets: [] },
    };

  const budgets = await prisma.budget.findMany({
    where: {
      user: { email: session.user.email }
    },
  });

  return {
    props: { budgets },
  };
}

export default function Home({ budgets }: Props) {

  const { status } = useSession();

  return (
    <>
      <Head>
        <title>BudTrackr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        { status === 'authenticated' ? 
        <Flex alignItems='center'>
          <Heading size='lg'>Dashboard</Heading>
          <Spacer />
          <NewBudget />
        </Flex>
        :
        <>
        <Text mt='8'>Please sign in to continue...</Text>
          <Stack mt='4'>
            <Skeleton height='12vh'/>
            <Skeleton height='12vh'/>
            <Skeleton height='12vh'/>
          </Stack>
        </>
        }
        <Stack mt='4' spacing='4'>
          {Object.values(budgets).map((budget) => (
            <NextLink href={`/b/${budget.id}`} key={budget.id}>
              <Card variant='outline'>
                <CardBody>
                  <Flex alignItems='center'>
                    <Box>
                      <Heading size='md' mb='1'>{budget.name}</Heading>
                      <Text fontSize='sm' color='grey'>{budget.desc}</Text>
                    </Box>
                    <Spacer />
                    <CircularProgress
                      thickness='8'
                      min={0}
                      max={budget.budget}
                      value={budget.expend}
                    >
                      <CircularProgressLabel>
                        {(budget.expend / budget.budget * 100).toFixed(0)}%
                      </CircularProgressLabel>
                    </CircularProgress>
                  </Flex>
                </CardBody>
              </Card>
            </NextLink>
          ))}
        </Stack>
      </Layout>
    </>
  );
}

